// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  active: string;
  background: string;
  buttonContainer: string;
  buttonDisabled: string;
  buttonReset: string;
  buttonSubmit: string;
  container: string;
  content: string;
  formWrap: string;
  itemContainer: string;
  itemWrap: string;
  kitchenFilter: string;
  slideInFromBottom: string;
  sortFilter: string;
}
export const cssExports: CssExports;
export default cssExports;
