// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  activeTab: string;
  tab: string;
  tabButton: string;
  tabsContainer: string;
}
export const cssExports: CssExports;
export default cssExports;
