// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  agreement: string;
  body: string;
  closeButton: string;
  container: string;
  contant: string;
  formFieldWrap: string;
  loginConnections: string;
  loginConnectionsData: string;
  loginConnectionsLinks: string;
  loginConnectionsTitle: string;
  loginForm: string;
  loginTitle: string;
  overlay: string;
}
export const cssExports: CssExports;
export default cssExports;
