// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  badge: string;
  cards: string;
  image: string;
  infoContainer: string;
  orderSum: string;
  orderTime: string;
  rating: string;
  specContainer: string;
  vendorName: string;
}
export const cssExports: CssExports;
export default cssExports;
