// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  buscketContainer: string;
  buttonContainer: string;
  header: string;
  headerContainer: string;
  headerWrapper: string;
  logoWrap: string;
}
export const cssExports: CssExports;
export default cssExports;
