// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  backLayer: string;
  iconsLeft: string;
  iconsRight: string;
  inputContainer: string;
  inputWrap: string;
  left: string;
  listWrap: string;
  searchContainer: string;
}
export const cssExports: CssExports;
export default cssExports;
