// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  addresContainer: string;
  filtersContainer: string;
  geoContainer: string;
  inputWrap: string;
  listWrap: string;
  openInput: string;
}
export const cssExports: CssExports;
export default cssExports;
