// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  buttonContainer: string;
  container: string;
  content: string;
  formWrap: string;
  itemWrap: string;
}
export const cssExports: CssExports;
export default cssExports;
