// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  addresContainer: string;
  backLayer: string;
  filtersContainer: string;
  geoContainer: string;
  inputContainer: string;
  listWrap: string;
  openInput: string;
  searchWrap: string;
}
export const cssExports: CssExports;
export default cssExports;
