// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  buttonWrap: string;
  container: string;
  left: string;
  right: string;
  wrap: string;
}
export const cssExports: CssExports;
export default cssExports;
