// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  iconWrap: string;
  textWrap: string;
  wrap: string;
}
export const cssExports: CssExports;
export default cssExports;
